 apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.sockets.appName }}
  labels:
    app: {{ .Values.sockets.appName }}
spec:
  replicas: {{ .Values.sockets.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.sockets.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.sockets.appName }}
    spec:
      containers:
        - name: {{ .Values.sockets.appName }}
          image: {{ .Values.sockets.image.repository }}:{{ .Values.sockets.image.tag }}
          command: ["gunicorn", "--bind",  "0.0.0.0:8000", "betteropinions.asgi:application"]
          args: [ "-w", "2", "-k", "uvicorn.workers.UvicornWorker"]
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
          resources:
            requests:
              memory: {{ .Values.sockets.resources.requests.memory }}
              cpu: {{ .Values.sockets.resources.requests.cpu }}
            limits:
              memory: {{ .Values.sockets.resources.limits.memory }}
              cpu: {{ .Values.sockets.resources.limits.cpu }}
