global:
  environment: staging
  project_id: bo-stage
  region: asia-south1

configMap:
  name: better-backend-app-config

django:
  appName: better-backend-app-django
  host: {{ .Values.HOST_NAME }} #api.prod-betteropinions.com
  image:
    repository: asia-south1-docker.pkg.dev/bo-prod-445611/bo-main/django-backend #For Production
    
                #Below is for Staging
                #asia-south1-docker.pkg.dev/bo-stage/bo-main/2024-11-01-new
    tag: 20250123-44
  replicas: 1

specs:
  staging:
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 3
        memory: 6Gi
  production:
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 3
        memory: 6Gi
