global:
  environment: staging

configMap:
  name: better-backend-app-config

django:
  appName: better-backend-app-django
  host: {{ .Values.HOST_NAME }} #api.prod-betteropinions.com
  image:
    repository: asia-south1-docker.pkg.dev/bo-prod-445611/bo-main/django-backend #For Production
    
                #Below is for Staging
                #asia-south1-docker.pkg.dev/bo-stage/bo-main/2024-11-01-new
    tag: 20250123-44
  replicas: 1
  resources:
    requests:
      cpu: {{ .Values.REQUESTS_CPU }}
      memory: {{ .Values.REQUESTS_MEMORY }}
    limits:
      cpu: {{ .Values.LIMITS_CPU }}
      memory: {{ .Values.LIMITS_MEMORY }}
