apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.beat.appName }}
  labels:
    app: {{ .Values.beat.appName }}
spec:
  replicas: {{ .Values.beat.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.beat.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.beat.appName }}
    spec:
      containers:
        - name: {{ .Values.beat.appName }}
          image: {{ .Values.beat.image.repository }}:{{ .Values.beat.image.tag }}
          command: ["/bin/bash", "config/celery_beat_worker.sh"]
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
          resources:
             resources:
{{- if eq .Values.global.environment "staging" }}
{{ toYaml .Values.environments.staging.resources | indent 12 }}
{{- else if eq .Values.global.environment "production" }}
{{ toYaml .Values.environments.production.resources | indent 12 }}
{{- else }}
{{ toYaml .Values.environments.staging.resources | indent 12 }}  # Default to staging if environment is not specified
{{- end }}
