global:
  environment: staging

configMap:
  name: better-backend-app-config

streamer:
  appName: better-backend-app-streamer
  image:
    repository: asia-south1-docker.pkg.dev/bo-prod-445611/bo-main/django-backend #For Production
    
                #Below is for Staging
                #asia-south1-docker.pkg.dev/bo-stage/bo-main/2024-11-01-new
    tag: 20250123-44
  replicas: 1
  resources:
    requests:
      cpu: ${{ vars.REQUESTS_CPU }}
      memory: ${{ vars.REQUESTS_MEMORY }}
    limits:
      cpu: ${{ vars.LIMITS_CPU }}
      memory: ${{ vars.LIMITS_MEMORY }}
