apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.django.appName }}
  labels:
    app: {{ .Values.django.appName }}
spec:
  replicas: {{ .Values.django.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.django.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.django.appName }}
    spec:
      containers:
        - name: {{ .Values.django.appName }}
          image: {{ .Values.django.image.repository }}:{{ .Values.django.image.tag }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
          resources:
    {{- if eq .Values.global.environment "staging" }}
    {{ toYaml .Values.environments.staging.resources | indent 12 }}
    {{- else if eq .Values.global.environment "production" }}
    {{ toYaml .Values.environments.production.resources | indent 12 }}
    {{- else }}
    {{ toYaml .Values.environments.staging.resources | indent 12 }}  # Default to staging if environment is not specified
    {{- end }}
          # livenessProbe:
          #   httpGet:
          #       path: /health/
          #       port: 8000
          #   initialDelaySeconds: 10
          #   periodSeconds: 15
          #   failureThreshold: 5
          #   successThreshold: 1
          # readinessProbe:
          #   httpGet:
          #       path: /health/
          #       port: 8000
          #   initialDelaySeconds: 10
          #   periodSeconds: 15
          #   failureThreshold: 5
          #   successThreshold: 1
