apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.django.appName }}
  labels:
    app: {{ .Values.django.appName }}
spec:
  replicas: {{ .Values.django.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.django.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.django.appName }}
    spec:
      containers:
        - name: {{ .Values.django.appName }}
          image: {{ .Values.global.region }}-docker.pkg.dev/{{ .Values.global.project_id }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
          resources:
            {{- if eq .Values.global.environment "production" }}
            {{- toYaml .Values.django.resources.production | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.django.resources.staging | nindent 12 }}
            {{- end }}
          # livenessProbe:
          #   httpGet:
          #       path: /health/
          #       port: 8000
          #   initialDelaySeconds: 10
          #   periodSeconds: 15
          #   failureThreshold: 5
          #   successThreshold: 1
          # readinessProbe:
          #   httpGet:
          #       path: /health/
          #       port: 8000
          #   initialDelaySeconds: 10
          #   periodSeconds: 15
          #   failureThreshold: 5
          #   successThreshold: 1
