apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.migration.appName }}
  labels:
    app: {{ .Values.migration.appName }}
spec:
  replicas: {{ .Values.migration.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.migration.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.migration.appName }}
    spec:
      containers:
        - name: {{ .Values.migration.appName }}
          image: {{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}
          command: ["python", "manage.py", "custom_migrate"]
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
          resources:
            requests:
              memory: {{ .Values.migration.resources.requests.memory }}
              cpu: {{ .Values.migration.resources.requests.cpu }}
            limits:
              memory: {{ .Values.migration.resources.limits.memory }}
              cpu: {{ .Values.migration.resources.limits.cpu }}
