name: Deploy Certificates and Ingress

on:
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/install.yml
    secrets: inherit
    
  deploy:
    needs: setup
    runs-on: ubuntu-22.04
    environment: ${{ github.event.inputs.environment }}  # Use the selected environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GCP authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.2
        with:
          project_id: ${{ vars.project_id }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials "${{ vars.GKE_CLUSTER }}" --zone "${{ vars.GKE_ZONE }}" --project "${{ vars.PROJECT_ID }}"

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Create Static IP for GKE Ingress
        run: |
          gcloud compute addresses create gce-ingress-static-ip --global || true

      - name: Create ManagedCertificate
        run: |
          kubectl apply -f ./ssl/certificate.yaml
          
      - name: Deploy Ingress
        run: |
          helm upgrade --install django-ingress ./ingress
