name: Install and Setup

on:
  workflow_call:

jobs:
  install:
    name: Install and Setup
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}  # Use the selected environment or default to 'staging'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Debug Environment Variables
      run: |
        echo "Selected Environment: ${{ inputs.environment || 'staging' }}"
        echo "PROJECT_ID: ${{ env.PROJECT_ID }}"
        echo "GKE_CLUSTER: ${{ env.GKE_CLUSTER }}"
        echo "GKE_ZONE: ${{ env.GKE_ZONE }}"
        echo "GCP_SA_KEY: ${{ secrets.GCP_SA_KEY != '' ? '*****' : 'NOT SET' }}"

    - name: Set up GCP authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # Access secret from the selected environment

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2.1.2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}  # Access secret from the selected environment
        project_id: ${{ env.PROJECT_ID }}  # Access env var from the selected environment

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin
        echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials "${{ env.GKE_CLUSTER }}" --zone "${{ env.GKE_ZONE }}" --project "${{ env.PROJECT_ID }}"

    - name: Verify kubectl configuration
      run: |
        kubectl config view
        kubectl cluster-info

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Verify Helm installation
      run: |
        helm version
