name: Deploy Redis to GKE 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (staging/production)'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  setup:
    uses: ./.github/workflows/install.yml
    secrets: inherit
    
  deploy:
    needs: setup
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up GCP authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2.1.2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ vars.PROJECT_ID }}

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin
        echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV
        
    - name: Get GKE credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

    - name: Verify kubectl configuration
      run: |
        kubectl config view
        kubectl cluster-info

    - name: Create Namespace
      run: |
        kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
        
    - name: Add Bitnami Helm Repository
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update
        
    - name: Deploy Redis
      run: |
        helm upgrade --install $DEPLOYMENT_NAME bitnami/redis \
          --namespace $NAMESPACE \
          --values ./redis/values.yaml \
          
          
    - name: Verify Deployment
      run: |
        kubectl get pods -n $NAMESPACE
        kubectl get svc -n $NAMESPACE
